site_name: Laravel Admin Panel
pages:
- index.md
- Instalation.md
- config.md
- Authentication.md
- The ACL.md
- Master View.md
- The Menu.md
- Simple Table Builder.md
- Flash Messages.md
- license.md
- changelog.md
theme: material
